[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.build]
cmds = ["cd jludating-api && npm install && npm run build && npx prisma generate"]

[phases.start]
cmds = ["cd jludating-api && npm run start:prod"]
